#### python -m pip install numpy

In [ ]:
import numpy as np

: 

#### Create an array of 10 zeros 

In [ ]:
np.zeros(10,dtype= "int")

: 

#### Create an array of 10 ones

In [ ]:
np.ones(10,dtype= "int")

#### Create an array of 10 fives

In [ ]:
np.ones(10,dtype= "int") * 5

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3,dtype="int")

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(3,3)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

#### Create the following matrix:

In [ ]:
np.arange(1,101).reshape(10,10) /  100

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0,1,20)

#### Create an array from a regular Python list or tuple using the array function.

In [ ]:
np.array([0,1,2, 3, 4,5,6,7,8]).reshape(3,3)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2:,1:]

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [98]:
mat[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [99]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [100]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [101]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [102]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [103]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
mat

In [106]:
mat.sum(axis =0)

325

In [108]:
mat.max(axis = 1)

array([ 5, 10, 15, 20, 25])

In [111]:
temp = np.array([1,2,3,1,2,3,1,2,3]).reshape(3,3)
temp
b_filt = temp>=2
temp[b_filt]

array([2, 3, 2, 3, 2, 3])